export const locationsEndpoints = {
  cities: '/department/',
  createCity: '/department/create',
  editCity: (id: number) => `/department/edit/${id}`,
  removeCity: (id: number) => `/department/remove/${id}`,
  buildings: '/subdivision/',
  createBuilding: '/subdivision/create',
  editBuilding: (id: number) => `/subdivision/edit/${id}`,
  removeBuilding: (id: number) => `/subdivision/remove/${id}`,
  cabinets: '/rooms/',
  createCabinet: '/rooms/create',
  editCabinet: (id: number) => `/rooms/edit/${id}`,
  removeCabinet: (id: number) => `/rooms/remove/${id}`,
  warehouses: '/storages',
  createWarehouse: '/storage',
  editWarehouse: (id: number) => `/storages/${id}`,
  employees: '/employees/',
  itemTypes: '/item-type',
} as const;
